language: node_js
node_js:
    - "8"
dist: trusty
services:
    - mongodb
env:
    - NODE_ENV=ci
cache:
    directories:
        - node_modules
# before_install:
#     - openssl aes-256-cbc -K $encrypted_787cea924d04_key -iv $encrypted_787cea924d04_iv
#       -in config/keyfile.json.enc -out keyfile.json -d

install:
    - npm install
    - npm run build
script:
    - nohup npm run start &
    - sleep 3
    - npm run test
# deploy:
#     - provider: gae
#     - keyfile: "config/keyfile.json.enc"
#     - project: "peerless-dahlia-229121"
#     - on: app-stable
