language: node_js
node_js:
    - "8"
dist: trusty
branches:
    only:
        - master
        - app-stable
        - api-stable
services:
    - mongodb
env:
    - NODE_ENV=ci
cache:
    directories:
        - node_modules

if: branch = app-stable
  before_install:
      - openssl aes-256-cbc -K $encrypted_787cea924d04_key -iv $encrypted_787cea924d04_iv
        -in config/keyfile.json.enc -out config/keyfile.json -d

  install:
      - npm install
      - npm run build
  script:
      # - nohup npm run start &
      # - sleep 3
      - npm run test
  deploy:
      - provider: gae
      - keyfile: "config/keyfile.json"
      - project: "peerless-dahlia-229121"
      - on: app-stable
# ADD THIS CODE TO API
# if: branch = api-stable
#     before_install:
#       - cd server
#     install:
#       - npm install
#     script:
#       - npm test
