language: node_js
node_js:
    - "8"
dist: trusty
branches:
    only:
        - master
        - app-stable
        - api-stable
services:
    - mongodb
env:
    - NODE_ENV=ci
cache:
    directories:
        - node_modules
before_install:
    - openssl aes-256-cbc -K $encrypted_464b4534abaf_key -iv $encrypted_464b4534abaf_iv
      -in config/keyfile.json.enc -out config/keyfile.json -d
install:
    - npm install
    - npm run build
script:
    - npm run test
deploy:
    - provider: gae
    - keyfile: config/keyfile.json
    - project: peerless-dahlia-229121
    - on:
          branch: app-stable
