language: node_js
node_js:
- '8'
dist: trusty
branches:
  only:
  - master
  - app-stable
  - api-stable
services:
- mongodb
env:
- NODE_ENV=ci
cache:
  directories:
  - node_modules
before_install:
- cd api/
- openssl aes-256-cbc -K $encrypted_dcc0d848680e_key -iv $encrypted_dcc0d848680e_iv
  -in config/credentials.tar.gz.enc -out config/credentials.tar.gz -d
- tar -C config/ -xzf config/credentials.tar.gz
- cat config/env.js
install:
- npm install
script:
- npm run test
deploy:
  provider: gae
  skip_cleanup: true
  keyfile: config/keyfile.json
  project: peerless-dahlia-229121
  on: api-stable
